project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "2023-12-02"
  chapters:
    - index.qmd
    - 20231202-2118_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2127_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2128_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2130_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2135_News_Mossad Team Meets with Qatar to Discuss Gaza Truce Restart.md
    - 20231202-2140_News_Mossad Team in Qatar to Discuss Gaza Truce Restart.md
    - 20231202-2141_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2146_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2150_News_US to Invest $3 Billion in Green Climate Fund.md
    - 20231202-2154_News_US to Invest $3 Billion in Green Climate Fund.md


format:
  html:
    theme: [cosmo, nord.scss,custom.scss]
  pdf:
    documentclass: scrreprt



