project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "2023-11-28"
  chapters:
    - index.qmd
    - 20231128-2316_News_Virgin Atlantic's Low-Carbon Fuel Powers Maiden Transatlantic Flight.md
    - 20231128-2324_News_Oil on Track for Losing Streak Amid Hopes of Further OPEC Cuts.md
    - 20231128-2327_News_Oil on Track for Snap Losing Streak on Hopes of Further OPEC Cuts.md
    - 20231128-2329_News_Virgin Atlantic's Low-Carbon Fuel Powers Maiden Transatlantic Flight.md
    - 20231128-2331_News_Indian Rescuers Close to Reaching Trapped Men in Tunnel.md
    - 20231128-2334_News_Futures Subdued Ahead of Fed Officials' Comments, Zscaler Falls.md
    - 20231128-2336_News_Eleven Workers Dead in Impala Platinum Mine Incident.md


format:
  html:
    theme: [cosmo, nord.scss,custom.scss]
  pdf:
    documentclass: scrreprt



