project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "11/10/2023"
  chapters:
    - index.qmd
    - 20231110-1445_News_Gaza Hospitals Under Attack by Israeli Forces - Reuters.md


format:
  html:
    theme: [cosmo,custom.scss]
  pdf:
    documentclass: scrreprt



