project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "2023-12-26"
  chapters:
    - index.qmd
    - 20231226-2323_News_Israel grants Intel $3.2 billion for new $25 billion chip plant.md
    - 20231226-2322_News_China criticizes US sanctions on Russia's Arctic LNG-2 project.md


format:
  html:
    theme: [cosmo, nord.scss,custom.scss]
  pdf:
    documentclass: scrreprt



