project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "2023-12-09"
  chapters:
    - index.qmd
    - 20231209-1501_News_Futures Muted as Investors Await Payrolls Data and Interest Rate Clues.md
    - 20231209-1502_News_Oil Prices Decline Amid Weakened Asian Demand.md
    - 20231209-1503_News_Spain's Calvino to be Next Head of European Investment Bank.md
    - 20231209-1503_News_UK Antitrust Regulator Considering Microsoft-OpenAI Partnership.md
    - 20231209-1504_News_Australia Swelters in Heat Wave, Faces Bushfire Risk.md


format:
  html:
    theme: [cosmo, nord.scss,custom.scss]
  pdf:
    documentclass: scrreprt



