project:
  type: book

book:
  title: "News"
  author: "lee"
  date: "2023-12-01"
  chapters:
    - index.qmd
    - 20231201-1142_News_China's Evergrande Seeks to Avoid Liquidation with Last-Ditch Debt Plan.md
    - 20231201-1144_News_Wall St. Futures Edge Higher on Easing Inflation Hopes.md


format:
  html:
    theme: [cosmo, nord.scss,custom.scss]
  pdf:
    documentclass: scrreprt



